version: "3.8"

services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URI: mongodb://db/matchingAds
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - matchingAds:/data/db

volumes:
  matchingAds:
